### ISSUE TITLE
MiniViT code no Transformation for MLP implement

### ISSUE THREAD

**Issue by zmqwer** [microsoft/Cream#118]
It seems that no implements of Transformation for MLP in MiniViT code

**Comment by wkcn** [comment]
Thanks for your attention to our work!

The transformation for MLP in MiniViT is implemented [as follow](https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py#L328-L332).
```python
# https://github.com/microsoft/Cream/blob/main/MiniViT/Mini-Swin/models/swin_transformer_minivit.py#L328-L332

if self.local_conv_list is not None:
    x = self.local_norm_list[layer_index](x)
    x = x.permute(0, 2, 1).view(B, C, H, W)
    # The transformation of MLP
    x = x + self.local_conv_list[layer_index](x)
    x = x.view(B, C, H * W).permute(0, 2, 1)

norm2 = self.norm2_list[layer_index] if self.is_sep_layernorm else self.norm2

# MLP
x = x + self.drop_path[layer_index](self.mlp(norm2(x)))
```

For each dimension $y_d$, a non-shared linear transformation $C^{(d)}$ is applied on all tokens (NxN tokens).
Since the number of parameters and the computational cost are too large, we resort a depth-wise convolution `self.local_conv_list[layer_index]` to sparsify it.
