### ISSUE TITLE
What is the input size of EfficientViT object detection performance

### ISSUE THREAD

**Issue by BUG1989** [microsoft/Cream#170]
We want to export the detection model to onnx, so what is the input shape of the RetinaNet Object Detection? Thanks a lot.

**Comment by xinyuliu-jeffrey** [comment]
Hi,

Thanks for your interest. We use the default resolution in mmdetection, i.e. max long side 1333 and max short side 800, as shown here https://github.com/microsoft/Cream/blob/ef68993c764f241a768cd69a087ed567dec6cb40/EfficientViT/downstream/configs/_base_/datasets/coco_detection.py#L19.

**Comment by BUG1989** [comment]
Could you please provide the ONNX format models of  RetinaNet Object Detection, we try to export it, but failed.

**Comment by xinyuliu-jeffrey** [comment]
Hi @BUG1989 ,

Since the detectors are inherited from the mmdet implementation and we use all the default configs, you may try exporting the pytorch to onnx according to https://mmdetection.readthedocs.io/en/v2.19.1/tutorials/pytorch2onnx.html. However, according to the mmdet team, this onnx export feature is expeimental at present, so some features might be unsupported. Hope this helps. Thank you. 

Best,
Xinyu
