### ISSUE TITLE
About rpe_ops

### ISSUE THREAD

**Issue by Zhong1015** [microsoft/Cream#205]
Hello,@wkcn. After using your IRPE module, I've noticed a certain improvement in my model's performance. However, in the 'rpe_ops' section, following the steps you provided, I still encounter the following warning message while running the code: "UserWarning: [WARNING] The module rpe_ops is not built. For better training performance, please build rpe_ops." I have two questions regarding this matter: ① Will using 'rpe_ops' affect the accuracy of the model, or will it only reduce training time? ② Even after following your instructions, I'm still receiving this warning. Do I need to perform additional actions concerning the 'nvcc' you mentioned?

**Comment by wkcn** [comment]
The reason is that the module `rpe_ops` imports failed.
`from rpe_ops.rpe_index import RPEIndexFunction`(https://github.com/microsoft/Cream/blob/main/iRPE/DETR-with-iRPE/models/rpe_attention/irpe.py#L9).
You can remove the statement `try-catch` and check why it imports failed.

It does not affect the accuracy. It only reduce training time.

**Comment by Zhong1015** [comment]
Thank you for your reply! I have solved the problem.
